var icebreakers = [
'¿Cuál es tu raza favorita de perros?',
'¿Cuál es tu primer recuerdo del internet?',
'¿Qué cosa te hace nerdear (nerd about)?',
'¿Cuál es tu sandwich favorito?',
'¿Cuál es una palabra que sabes pero que nunca has sabido pronunciar?',
'Si el universo te devolviera un objeto que perdiste, ¿cuál sería?',
'¿Alguna vez has visto un fantasma?',
'¿Cuál es tu programa de televisión favorito?',
'¿Cuál es el dato MENOS interesante de ti mismo?',
'¿Hay algo de tu infancia que siga siendo cierto sobre ti hoy? ¿Qué cosa?',
'¿Cuál es la mejor película/serie en alguna plataforma hoy?',
'¿Música favorita de los 90s?',
'¿Película favorita de los 90s?',
'¿Peor corte de pelo?',
'¿Comida de fiestas (holiday) favorita?',
'¿Restaurante favorito en la ciudad? ¿Qué sueles pedir?',
'¿Lugar favorito para caminar?',
'¿Cuál es el cumplido más insultante que hayas recibido?',
'¿Qué comida odiabas en tu infancia que ahora amas?',
'¿Cuál es tu habilidad más inútil?',	
'¿Cuál es la película que más citas?',
'¿Cuál es tu snack favorito para ver televisión?',
'¿Cuál es tu comida reconfortante (comfort food) favorita?',
'¿Primer concierto, mejor concierto, peor concierto?',
'¿Cuál es el primer libro que recuerdas que causó gran impacto en ti?',
'¿Cuál es una creencia rara o malentendido que tuviste por mucho tiempo?',
'Estás construyendo la casa de tus sueños... ¿qué cuarto o característica debe incluir?',
'¿Coleccionas algo? Si sí, ¿qué?',
'¿Quién ha sido tu profesor favorito de la escuela y por qué?',
'¿Cuál es tu aparato o utensilio de cocina favorito?',
'Describe tus gustos musicales usando una comida.',
'¿Actividad favorita para un día de nieve?',
'¿Qué objeto has perdido que te gustaría que el universo te regresara?',
'¿Cuál es tu lugar favorito?',
'¿Qué es algo que siempre te emocione o alegre?',
'¿Qué comida odias?',
'¿Cuál es tu postre favorito?',
'Si tuvieras que vivir en un mundo de una película como un personaje secundario, ¿qué película sería?',
'¿Cuál es tu tipografía favorita?',
'¿Cuál es tu bebida favorita?'
]

function newIcebreaker() {
	var randomNumber = Math.floor(Math.random() * (icebreakers.length));
	document.getElementById('icebreakerDisplay').innerHTML = icebreakers[randomNumber];
}
